name: Linux

# Trigger this workflow on push or pull request
on: [push, pull_request]

jobs:
  build:
    name: Build and test

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Install dependencies
      with:
        packages:
          git
          build-essential
          cmake
          ninja-build
        update: true
          
    - uses: actions/checkout@v2
       
    - name: CMake configure
      run: |
        cd build
        cmake .. -GNinja

    - name: Shader
      run: |
        cd build
        ninja
